package(default_visibility = ["//visibility:public"])

cc_library(
    name = "hash_table_lib",
    srcs = [
        "densehashtable.h",
        "sparsehashtable.h",
    ],
    hdrs = [
        "libc_allocator_with_realloc.h",
        "hashtable-common.h",
    ]
)
